/*
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pluxbox.radiomanager.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pluxbox.radiomanager.api.models.BroadcastRelationsModelType;
import com.pluxbox.radiomanager.api.models.Contact;
import com.pluxbox.radiomanager.api.models.ContactOutputOnly;
import com.pluxbox.radiomanager.api.models.ContactRelations;
import com.pluxbox.radiomanager.api.models.ContactRelationsItems;
import com.pluxbox.radiomanager.api.models.ContactRelationsTags;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContactResult
 */
public class ContactResultTest {
    private final ContactResult model = new ContactResult();

    /**
     * Model tests for ContactResult
     */
    @Test
    public void testContactResult() {
        // TODO: test ContactResult
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'updatedAt'
     */
    @Test
    public void updatedAtTest() {
        // TODO: test updatedAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'externalStationId'
     */
    @Test
    public void externalStationIdTest() {
        // TODO: test externalStationId
    }

    /**
     * Test the property 'modelTypeId'
     */
    @Test
    public void modelTypeIdTest() {
        // TODO: test modelTypeId
    }

    /**
     * Test the property 'fieldValues'
     */
    @Test
    public void fieldValuesTest() {
        // TODO: test fieldValues
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'firstname'
     */
    @Test
    public void firstnameTest() {
        // TODO: test firstname
    }

    /**
     * Test the property 'lastname'
     */
    @Test
    public void lastnameTest() {
        // TODO: test lastname
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'tags'
     */
    @Test
    public void tagsTest() {
        // TODO: test tags
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

    /**
     * Test the property 'modelType'
     */
    @Test
    public void modelTypeTest() {
        // TODO: test modelType
    }

}
