/*
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pluxbox.radiomanager.api.models;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsBroadcasts;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsCampaigns;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsContacts;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsItems;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsPresenters;
import com.pluxbox.radiomanager.api.models.ModelTypeRelationsPrograms;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ModelTypeRelations
 */
public class ModelTypeRelationsTest {
    private final ModelTypeRelations model = new ModelTypeRelations();

    /**
     * Model tests for ModelTypeRelations
     */
    @Test
    public void testModelTypeRelations() {
        // TODO: test ModelTypeRelations
    }

    /**
     * Test the property 'campaigns'
     */
    @Test
    public void campaignsTest() {
        // TODO: test campaigns
    }

    /**
     * Test the property 'broadcasts'
     */
    @Test
    public void broadcastsTest() {
        // TODO: test broadcasts
    }

    /**
     * Test the property 'programs'
     */
    @Test
    public void programsTest() {
        // TODO: test programs
    }

    /**
     * Test the property 'contacts'
     */
    @Test
    public void contactsTest() {
        // TODO: test contacts
    }

    /**
     * Test the property 'presenters'
     */
    @Test
    public void presentersTest() {
        // TODO: test presenters
    }

    /**
     * Test the property 'items'
     */
    @Test
    public void itemsTest() {
        // TODO: test items
    }

}
