/*
 * RadioManager
 * RadioManager
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pluxbox.radiomanager.api.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.pluxbox.radiomanager.api.models.ImportItem;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * InlineObject
 */

public class InlineObject {
  public static final String SERIALIZED_NAME_START = "start";
  @SerializedName(SERIALIZED_NAME_START)
  private OffsetDateTime start;

  public static final String SERIALIZED_NAME_ALLOW_PLAYLIST_PAST = "allow_playlist_past";
  @SerializedName(SERIALIZED_NAME_ALLOW_PLAYLIST_PAST)
  private Integer allowPlaylistPast;

  public static final String SERIALIZED_NAME_ITEMS = "items";
  @SerializedName(SERIALIZED_NAME_ITEMS)
  private List<ImportItem> items = null;


  public InlineObject start(OffsetDateTime start) {
    
    this.start = start;
    return this;
  }

   /**
   * Get start
   * @return start
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "2017-06-23T12:00+02:00", value = "")

  public OffsetDateTime getStart() {
    return start;
  }


  public void setStart(OffsetDateTime start) {
    this.start = start;
  }


  public InlineObject allowPlaylistPast(Integer allowPlaylistPast) {
    
    this.allowPlaylistPast = allowPlaylistPast;
    return this;
  }

   /**
   * Get allowPlaylistPast
   * @return allowPlaylistPast
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "0", value = "")

  public Integer getAllowPlaylistPast() {
    return allowPlaylistPast;
  }


  public void setAllowPlaylistPast(Integer allowPlaylistPast) {
    this.allowPlaylistPast = allowPlaylistPast;
  }


  public InlineObject items(List<ImportItem> items) {
    
    this.items = items;
    return this;
  }

  public InlineObject addItemsItem(ImportItem itemsItem) {
    if (this.items == null) {
      this.items = new ArrayList<>();
    }
    this.items.add(itemsItem);
    return this;
  }

   /**
   * Get items
   * @return items
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<ImportItem> getItems() {
    return items;
  }


  public void setItems(List<ImportItem> items) {
    this.items = items;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineObject inlineObject = (InlineObject) o;
    return Objects.equals(this.start, inlineObject.start) &&
        Objects.equals(this.allowPlaylistPast, inlineObject.allowPlaylistPast) &&
        Objects.equals(this.items, inlineObject.items);
  }

  @Override
  public int hashCode() {
    return Objects.hash(start, allowPlaylistPast, items);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineObject {\n");
    sb.append("    start: ").append(toIndentedString(start)).append("\n");
    sb.append("    allowPlaylistPast: ").append(toIndentedString(allowPlaylistPast)).append("\n");
    sb.append("    items: ").append(toIndentedString(items)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

