/*
 * RadioManager
 * RadioManager
 *
 * OpenAPI spec version: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.pluxbox.radiomanager.api.models;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;

/**
 * StationResultStation
 */

public class StationResultStation {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("created_at")
  private OffsetDateTime createdAt = null;

  @SerializedName("updated_at")
  private OffsetDateTime updatedAt = null;

  @SerializedName("system_name")
  private String systemName = null;

  @SerializedName("short_name")
  private String shortName = null;

  @SerializedName("medium_name")
  private String mediumName = null;

  @SerializedName("website")
  private String website = null;

  @SerializedName("email")
  private String email = null;

  @SerializedName("keywords")
  private List<String> keywords = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("sms")
  private String sms = null;

  @SerializedName("telephone")
  private String telephone = null;

  @SerializedName("genre_id")
  private Integer genreId = null;

  @SerializedName("language")
  private String language = null;

  @SerializedName("active")
  private Boolean active = null;

  @SerializedName("logo_rectangle")
  private String logoRectangle = null;

  @SerializedName("logo_128x128")
  private String logo128x128 = null;

  @SerializedName("logo_320x320")
  private String logo320x320 = null;

  @SerializedName("logo_600x600")
  private String logo600x600 = null;

  @SerializedName("pay_off")
  private String payOff = null;

  @SerializedName("pty_code")
  private Integer ptyCode = null;

  @SerializedName("pty_type")
  private String ptyType = null;

  @SerializedName("station_key")
  private String stationKey = null;

  @SerializedName("timezone")
  private String timezone = null;

  @SerializedName("trial_date")
  private OffsetDateTime trialDate = null;

  public StationResultStation id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(example = "1", value = "")
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public StationResultStation name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(example = "stationname", value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public StationResultStation createdAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @ApiModelProperty(example = "2016-01-11T22:01:11+02:00", value = "")
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public StationResultStation updatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
    return this;
  }

   /**
   * Get updatedAt
   * @return updatedAt
  **/
  @ApiModelProperty(example = "2016-01-11T22:01:11+02:00", value = "")
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }

  public StationResultStation systemName(String systemName) {
    this.systemName = systemName;
    return this;
  }

   /**
   * Get systemName
   * @return systemName
  **/
  @ApiModelProperty(example = "stationname", value = "")
  public String getSystemName() {
    return systemName;
  }

  public void setSystemName(String systemName) {
    this.systemName = systemName;
  }

  public StationResultStation shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }

   /**
   * Get shortName
   * @return shortName
  **/
  @ApiModelProperty(example = "stationname", value = "")
  public String getShortName() {
    return shortName;
  }

  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public StationResultStation mediumName(String mediumName) {
    this.mediumName = mediumName;
    return this;
  }

   /**
   * Get mediumName
   * @return mediumName
  **/
  @ApiModelProperty(example = "stationname", value = "")
  public String getMediumName() {
    return mediumName;
  }

  public void setMediumName(String mediumName) {
    this.mediumName = mediumName;
  }

  public StationResultStation website(String website) {
    this.website = website;
    return this;
  }

   /**
   * Get website
   * @return website
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getWebsite() {
    return website;
  }

  public void setWebsite(String website) {
    this.website = website;
  }

  public StationResultStation email(String email) {
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @ApiModelProperty(example = "station@name.com", value = "")
  public String getEmail() {
    return email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public StationResultStation keywords(List<String> keywords) {
    this.keywords = keywords;
    return this;
  }

  public StationResultStation addKeywordsItem(String keywordsItem) {
    if (this.keywords == null) {
      this.keywords = new ArrayList<String>();
    }
    this.keywords.add(keywordsItem);
    return this;
  }

   /**
   * Get keywords
   * @return keywords
  **/
  @ApiModelProperty(value = "")
  public List<String> getKeywords() {
    return keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public StationResultStation description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @ApiModelProperty(example = "description", value = "")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public StationResultStation sms(String sms) {
    this.sms = sms;
    return this;
  }

   /**
   * Get sms
   * @return sms
  **/
  @ApiModelProperty(example = "00313552222222", value = "")
  public String getSms() {
    return sms;
  }

  public void setSms(String sms) {
    this.sms = sms;
  }

  public StationResultStation telephone(String telephone) {
    this.telephone = telephone;
    return this;
  }

   /**
   * Get telephone
   * @return telephone
  **/
  @ApiModelProperty(example = "00313552222222", value = "")
  public String getTelephone() {
    return telephone;
  }

  public void setTelephone(String telephone) {
    this.telephone = telephone;
  }

  public StationResultStation genreId(Integer genreId) {
    this.genreId = genreId;
    return this;
  }

   /**
   * Get genreId
   * @return genreId
  **/
  @ApiModelProperty(example = "3571", value = "")
  public Integer getGenreId() {
    return genreId;
  }

  public void setGenreId(Integer genreId) {
    this.genreId = genreId;
  }

  public StationResultStation language(String language) {
    this.language = language;
    return this;
  }

   /**
   * Get language
   * @return language
  **/
  @ApiModelProperty(example = "Dutch", value = "")
  public String getLanguage() {
    return language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public StationResultStation active(Boolean active) {
    this.active = active;
    return this;
  }

   /**
   * Get active
   * @return active
  **/
  @ApiModelProperty(example = "true", value = "")
  public Boolean getActive() {
    return active;
  }

  public void setActive(Boolean active) {
    this.active = active;
  }

  public StationResultStation logoRectangle(String logoRectangle) {
    this.logoRectangle = logoRectangle;
    return this;
  }

   /**
   * Get logoRectangle
   * @return logoRectangle
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getLogoRectangle() {
    return logoRectangle;
  }

  public void setLogoRectangle(String logoRectangle) {
    this.logoRectangle = logoRectangle;
  }

  public StationResultStation logo128x128(String logo128x128) {
    this.logo128x128 = logo128x128;
    return this;
  }

   /**
   * Get logo128x128
   * @return logo128x128
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getLogo128x128() {
    return logo128x128;
  }

  public void setLogo128x128(String logo128x128) {
    this.logo128x128 = logo128x128;
  }

  public StationResultStation logo320x320(String logo320x320) {
    this.logo320x320 = logo320x320;
    return this;
  }

   /**
   * Get logo320x320
   * @return logo320x320
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getLogo320x320() {
    return logo320x320;
  }

  public void setLogo320x320(String logo320x320) {
    this.logo320x320 = logo320x320;
  }

  public StationResultStation logo600x600(String logo600x600) {
    this.logo600x600 = logo600x600;
    return this;
  }

   /**
   * Get logo600x600
   * @return logo600x600
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getLogo600x600() {
    return logo600x600;
  }

  public void setLogo600x600(String logo600x600) {
    this.logo600x600 = logo600x600;
  }

  public StationResultStation payOff(String payOff) {
    this.payOff = payOff;
    return this;
  }

   /**
   * Get payOff
   * @return payOff
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getPayOff() {
    return payOff;
  }

  public void setPayOff(String payOff) {
    this.payOff = payOff;
  }

  public StationResultStation ptyCode(Integer ptyCode) {
    this.ptyCode = ptyCode;
    return this;
  }

   /**
   * Get ptyCode
   * @return ptyCode
  **/
  @ApiModelProperty(example = "10", value = "")
  public Integer getPtyCode() {
    return ptyCode;
  }

  public void setPtyCode(Integer ptyCode) {
    this.ptyCode = ptyCode;
  }

  public StationResultStation ptyType(String ptyType) {
    this.ptyType = ptyType;
    return this;
  }

   /**
   * Get ptyType
   * @return ptyType
  **/
  @ApiModelProperty(example = "rds", value = "")
  public String getPtyType() {
    return ptyType;
  }

  public void setPtyType(String ptyType) {
    this.ptyType = ptyType;
  }

  public StationResultStation stationKey(String stationKey) {
    this.stationKey = stationKey;
    return this;
  }

   /**
   * Get stationKey
   * @return stationKey
  **/
  @ApiModelProperty(example = "none", value = "")
  public String getStationKey() {
    return stationKey;
  }

  public void setStationKey(String stationKey) {
    this.stationKey = stationKey;
  }

  public StationResultStation timezone(String timezone) {
    this.timezone = timezone;
    return this;
  }

   /**
   * Get timezone
   * @return timezone
  **/
  @ApiModelProperty(example = "Europe/Amsterdam", value = "")
  public String getTimezone() {
    return timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public StationResultStation trialDate(OffsetDateTime trialDate) {
    this.trialDate = trialDate;
    return this;
  }

   /**
   * Get trialDate
   * @return trialDate
  **/
  @ApiModelProperty(example = "2016-01-11", value = "")
  public OffsetDateTime getTrialDate() {
    return trialDate;
  }

  public void setTrialDate(OffsetDateTime trialDate) {
    this.trialDate = trialDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    StationResultStation stationResultStation = (StationResultStation) o;
    return Objects.equals(this.id, stationResultStation.id) &&
        Objects.equals(this.name, stationResultStation.name) &&
        Objects.equals(this.createdAt, stationResultStation.createdAt) &&
        Objects.equals(this.updatedAt, stationResultStation.updatedAt) &&
        Objects.equals(this.systemName, stationResultStation.systemName) &&
        Objects.equals(this.shortName, stationResultStation.shortName) &&
        Objects.equals(this.mediumName, stationResultStation.mediumName) &&
        Objects.equals(this.website, stationResultStation.website) &&
        Objects.equals(this.email, stationResultStation.email) &&
        Objects.equals(this.keywords, stationResultStation.keywords) &&
        Objects.equals(this.description, stationResultStation.description) &&
        Objects.equals(this.sms, stationResultStation.sms) &&
        Objects.equals(this.telephone, stationResultStation.telephone) &&
        Objects.equals(this.genreId, stationResultStation.genreId) &&
        Objects.equals(this.language, stationResultStation.language) &&
        Objects.equals(this.active, stationResultStation.active) &&
        Objects.equals(this.logoRectangle, stationResultStation.logoRectangle) &&
        Objects.equals(this.logo128x128, stationResultStation.logo128x128) &&
        Objects.equals(this.logo320x320, stationResultStation.logo320x320) &&
        Objects.equals(this.logo600x600, stationResultStation.logo600x600) &&
        Objects.equals(this.payOff, stationResultStation.payOff) &&
        Objects.equals(this.ptyCode, stationResultStation.ptyCode) &&
        Objects.equals(this.ptyType, stationResultStation.ptyType) &&
        Objects.equals(this.stationKey, stationResultStation.stationKey) &&
        Objects.equals(this.timezone, stationResultStation.timezone) &&
        Objects.equals(this.trialDate, stationResultStation.trialDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, createdAt, updatedAt, systemName, shortName, mediumName, website, email, keywords, description, sms, telephone, genreId, language, active, logoRectangle, logo128x128, logo320x320, logo600x600, payOff, ptyCode, ptyType, stationKey, timezone, trialDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StationResultStation {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    systemName: ").append(toIndentedString(systemName)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("    mediumName: ").append(toIndentedString(mediumName)).append("\n");
    sb.append("    website: ").append(toIndentedString(website)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    keywords: ").append(toIndentedString(keywords)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    sms: ").append(toIndentedString(sms)).append("\n");
    sb.append("    telephone: ").append(toIndentedString(telephone)).append("\n");
    sb.append("    genreId: ").append(toIndentedString(genreId)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    active: ").append(toIndentedString(active)).append("\n");
    sb.append("    logoRectangle: ").append(toIndentedString(logoRectangle)).append("\n");
    sb.append("    logo128x128: ").append(toIndentedString(logo128x128)).append("\n");
    sb.append("    logo320x320: ").append(toIndentedString(logo320x320)).append("\n");
    sb.append("    logo600x600: ").append(toIndentedString(logo600x600)).append("\n");
    sb.append("    payOff: ").append(toIndentedString(payOff)).append("\n");
    sb.append("    ptyCode: ").append(toIndentedString(ptyCode)).append("\n");
    sb.append("    ptyType: ").append(toIndentedString(ptyType)).append("\n");
    sb.append("    stationKey: ").append(toIndentedString(stationKey)).append("\n");
    sb.append("    timezone: ").append(toIndentedString(timezone)).append("\n");
    sb.append("    trialDate: ").append(toIndentedString(trialDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

