/*
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package radiomanager;

import com.pluxbox.radiomanager.api.invoker.ApiException;
import com.pluxbox.radiomanager.api.models.InlineResponse2009;
import com.pluxbox.radiomanager.api.models.InlineResponse400;
import com.pluxbox.radiomanager.api.models.InlineResponse401;
import com.pluxbox.radiomanager.api.models.InlineResponse403;
import com.pluxbox.radiomanager.api.models.InlineResponse404;
import com.pluxbox.radiomanager.api.models.InlineResponse422;
import com.pluxbox.radiomanager.api.models.InlineResponse429;
import com.pluxbox.radiomanager.api.models.InlineResponse500;
import com.pluxbox.radiomanager.api.models.ModelTypeResult;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ModelTypeApi
 */
@Disabled
public class ModelTypeApiTest {

    private final ModelTypeApi api = new ModelTypeApi();

    /**
     * Get modelType by id
     *
     * Get modelType by id
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getModelTypeByIdTest() throws ApiException {
        Long id = null;
        String orderDirection = null;
        Long externalStationId = null;
        ModelTypeResult response = api.getModelTypeById(id, orderDirection, externalStationId);
        // TODO: test validations
    }

    /**
     * Get all modelTypes.
     *
     * List all modelTypes.
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void listModelTypesTest() throws ApiException {
        Long programId = null;
        Long broadcastId = null;
        Long itemId = null;
        Long campaignId = null;
        Long presenterId = null;
        Long contactId = null;
        String model = null;
        String orderDirection = null;
        Long externalStationId = null;
        InlineResponse2009 response = api.listModelTypes(programId, broadcastId, itemId, campaignId, presenterId, contactId, model, orderDirection, externalStationId);
        // TODO: test validations
    }

}
