/*
 * RadioManager
 * This OpenAPI 3 Document describes the functionality of the API v2 of RadioManager. Note that no rights can be derived from this Document and the true functionality of the API might differ.
 *
 * The version of the OpenAPI document: 2.0
 * Contact: support@pluxbox.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.pluxbox.radiomanager.api.invoker;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.internal.bind.util.ISO8601Utils;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonElement;
import io.gsonfire.GsonFireBuilder;
import io.gsonfire.TypeSelector;

import okio.ByteString;

import java.io.IOException;
import java.io.StringReader;
import java.lang.reflect.Type;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.ParsePosition;
import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Date;
import java.util.Locale;
import java.util.Map;
import java.util.HashMap;

/*
 * A JSON utility class
 *
 * NOTE: in the future, this class may be converted to static, which may break
 *       backward-compatibility
 */
public class JSON {
    private static Gson gson;
    private static boolean isLenientOnJson = false;
    private static DateTypeAdapter dateTypeAdapter = new DateTypeAdapter();
    private static SqlDateTypeAdapter sqlDateTypeAdapter = new SqlDateTypeAdapter();
    private static OffsetDateTimeTypeAdapter offsetDateTimeTypeAdapter = new OffsetDateTimeTypeAdapter();
    private static LocalDateTypeAdapter localDateTypeAdapter = new LocalDateTypeAdapter();
    private static ByteArrayAdapter byteArrayAdapter = new ByteArrayAdapter();

    @SuppressWarnings("unchecked")
    public static GsonBuilder createGson() {
        GsonFireBuilder fireBuilder = new GsonFireBuilder()
        ;
        GsonBuilder builder = fireBuilder.createGsonBuilder();
        return builder;
    }

    private static String getDiscriminatorValue(JsonElement readElement, String discriminatorField) {
        JsonElement element = readElement.getAsJsonObject().get(discriminatorField);
        if (null == element) {
            throw new IllegalArgumentException("missing discriminator field: <" + discriminatorField + ">");
        }
        return element.getAsString();
    }

    /**
     * Returns the Java class that implements the OpenAPI schema for the specified discriminator value.
     *
     * @param classByDiscriminatorValue The map of discriminator values to Java classes.
     * @param discriminatorValue The value of the OpenAPI discriminator in the input data.
     * @return The Java class that implements the OpenAPI schema
     */
    private static Class getClassByDiscriminator(Map classByDiscriminatorValue, String discriminatorValue) {
        Class clazz = (Class) classByDiscriminatorValue.get(discriminatorValue);
        if (null == clazz) {
            throw new IllegalArgumentException("cannot determine model class of name: <" + discriminatorValue + ">");
        }
        return clazz;
    }

    {
        GsonBuilder gsonBuilder = createGson();
        gsonBuilder.registerTypeAdapter(Date.class, dateTypeAdapter);
        gsonBuilder.registerTypeAdapter(java.sql.Date.class, sqlDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(OffsetDateTime.class, offsetDateTimeTypeAdapter);
        gsonBuilder.registerTypeAdapter(LocalDate.class, localDateTypeAdapter);
        gsonBuilder.registerTypeAdapter(byte[].class, byteArrayAdapter);
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Block.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelationsBroadcast.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelationsBroadcastParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelationsItemsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockRelationsProgram.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BlockResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Broadcast.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastEPGDay.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastEPGRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastEPGResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastInputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsBlocks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsGenre.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsGroup.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsItemsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsModelType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsPresenters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastRelationsTags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.BroadcastResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Campaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignRelationsItemsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignTemplateItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.CampaignTemplateItemAllOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Contact.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactRelationsTags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactRelationsTagsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ContactResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.EPGResults.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Genre.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreRelationsBroadcastsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreRelationsPrograms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GenreResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Group.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupRelationsPrograms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupRelationsUsers.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupRelationsUsersParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.GroupResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ImportItem.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ImportItemAllOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse200.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2001.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse20010.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse20011.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse20012.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse20013.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2002.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2003.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2004.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2005.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2006.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2007.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2008.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2009.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse202.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse2021.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse400.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse401.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse403.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse404.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse422.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse429.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InlineResponse500.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.InviteUserData.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Item.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemAllOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemInputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsBlock.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsCampaign.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsContactsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsProgram.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemRelationsTags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ItemsStopcurrentBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeOptions.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsCampaigns.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsCampaignsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsPresenters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeRelationsPrograms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ModelTypeResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PlaylistMergeBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PlaylistStructureBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PlaylistTimingBody.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Presenter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterEPGResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterRelationsModelType.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterRelationsPrograms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterRelationsProgramsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.PresenterResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Program.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramInputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramInputOnlyAllOf.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsBlocks.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsItemsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsPresenters.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramRelationsTags.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.ProgramResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.StationResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.StationResultStation.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.StationResultStationStartDays.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.Tag.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagDataInput.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagOutputOnly.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelations.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelationsBroadcasts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelationsBroadcastsParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelationsContacts.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelationsItems.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagRelationsPrograms.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TagResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.TextString.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UnusedBooleanParameter.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UserResult.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UserResultGroups.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UserResultParams.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UserResultRoles.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.UserResultSettings.CustomTypeAdapterFactory());
        gsonBuilder.registerTypeAdapterFactory(new com.pluxbox.radiomanager.api.models.VisualResult.CustomTypeAdapterFactory());
        gson = gsonBuilder.create();
    }

    /**
     * Get Gson.
     *
     * @return Gson
     */
    public static Gson getGson() {
        return gson;
    }

    /**
     * Set Gson.
     *
     * @param gson Gson
     */
    public static void setGson(Gson gson) {
        JSON.gson = gson;
    }

    public static void setLenientOnJson(boolean lenientOnJson) {
        isLenientOnJson = lenientOnJson;
    }

    /**
     * Serialize the given Java object into JSON string.
     *
     * @param obj Object
     * @return String representation of the JSON
     */
    public static String serialize(Object obj) {
        return gson.toJson(obj);
    }

    /**
     * Deserialize the given JSON string to Java object.
     *
     * @param <T>        Type
     * @param body       The JSON string
     * @param returnType The type to deserialize into
     * @return The deserialized Java object
     */
    @SuppressWarnings("unchecked")
    public static <T> T deserialize(String body, Type returnType) {
        try {
            if (isLenientOnJson) {
                JsonReader jsonReader = new JsonReader(new StringReader(body));
                // see https://google-gson.googlecode.com/svn/trunk/gson/docs/javadocs/com/google/gson/stream/JsonReader.html#setLenient(boolean)
                jsonReader.setLenient(true);
                return gson.fromJson(jsonReader, returnType);
            } else {
                return gson.fromJson(body, returnType);
            }
        } catch (JsonParseException e) {
            // Fallback processing when failed to parse JSON form response body:
            // return the response body string directly for the String return type;
            if (returnType.equals(String.class)) {
                return (T) body;
            } else {
                throw (e);
            }
        }
    }

    /**
     * Gson TypeAdapter for Byte Array type
     */
    public static class ByteArrayAdapter extends TypeAdapter<byte[]> {

        @Override
        public void write(JsonWriter out, byte[] value) throws IOException {
            if (value == null) {
                out.nullValue();
            } else {
                out.value(ByteString.of(value).base64());
            }
        }

        @Override
        public byte[] read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String bytesAsBase64 = in.nextString();
                    ByteString byteString = ByteString.decodeBase64(bytesAsBase64);
                    return byteString.toByteArray();
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 OffsetDateTime type
     */
    public static class OffsetDateTimeTypeAdapter extends TypeAdapter<OffsetDateTime> {

        private DateTimeFormatter formatter;

        public OffsetDateTimeTypeAdapter() {
            this(DateTimeFormatter.ISO_OFFSET_DATE_TIME);
        }

        public OffsetDateTimeTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, OffsetDateTime date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public OffsetDateTime read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    if (date.endsWith("+0000")) {
                        date = date.substring(0, date.length()-5) + "Z";
                    }
                    return OffsetDateTime.parse(date, formatter);
            }
        }
    }

    /**
     * Gson TypeAdapter for JSR310 LocalDate type
     */
    public static class LocalDateTypeAdapter extends TypeAdapter<LocalDate> {

        private DateTimeFormatter formatter;

        public LocalDateTypeAdapter() {
            this(DateTimeFormatter.ISO_LOCAL_DATE);
        }

        public LocalDateTypeAdapter(DateTimeFormatter formatter) {
            this.formatter = formatter;
        }

        public void setFormat(DateTimeFormatter dateFormat) {
            this.formatter = dateFormat;
        }

        @Override
        public void write(JsonWriter out, LocalDate date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                out.value(formatter.format(date));
            }
        }

        @Override
        public LocalDate read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    return LocalDate.parse(date, formatter);
            }
        }
    }

    public static void setOffsetDateTimeFormat(DateTimeFormatter dateFormat) {
        offsetDateTimeTypeAdapter.setFormat(dateFormat);
    }

    public static void setLocalDateFormat(DateTimeFormatter dateFormat) {
        localDateTypeAdapter.setFormat(dateFormat);
    }

    /**
     * Gson TypeAdapter for java.sql.Date type
     * If the dateFormat is null, a simple "yyyy-MM-dd" format will be used
     * (more efficient than SimpleDateFormat).
     */
    public static class SqlDateTypeAdapter extends TypeAdapter<java.sql.Date> {

        private DateFormat dateFormat;

        public SqlDateTypeAdapter() {}

        public SqlDateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, java.sql.Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = date.toString();
                }
                out.value(value);
            }
        }

        @Override
        public java.sql.Date read(JsonReader in) throws IOException {
            switch (in.peek()) {
                case NULL:
                    in.nextNull();
                    return null;
                default:
                    String date = in.nextString();
                    try {
                        if (dateFormat != null) {
                            return new java.sql.Date(dateFormat.parse(date).getTime());
                        }
                        return new java.sql.Date(ISO8601Utils.parse(date, new ParsePosition(0)).getTime());
                    } catch (ParseException e) {
                        throw new JsonParseException(e);
                    }
            }
        }
    }

    /**
     * Gson TypeAdapter for java.util.Date type
     * If the dateFormat is null, ISO8601Utils will be used.
     */
    public static class DateTypeAdapter extends TypeAdapter<Date> {

        private DateFormat dateFormat;

        public DateTypeAdapter() {}

        public DateTypeAdapter(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        public void setFormat(DateFormat dateFormat) {
            this.dateFormat = dateFormat;
        }

        @Override
        public void write(JsonWriter out, Date date) throws IOException {
            if (date == null) {
                out.nullValue();
            } else {
                String value;
                if (dateFormat != null) {
                    value = dateFormat.format(date);
                } else {
                    value = ISO8601Utils.format(date, true);
                }
                out.value(value);
            }
        }

        @Override
        public Date read(JsonReader in) throws IOException {
            try {
                switch (in.peek()) {
                    case NULL:
                        in.nextNull();
                        return null;
                    default:
                        String date = in.nextString();
                        try {
                            if (dateFormat != null) {
                                return dateFormat.parse(date);
                            }
                            return ISO8601Utils.parse(date, new ParsePosition(0));
                        } catch (ParseException e) {
                            throw new JsonParseException(e);
                        }
                }
            } catch (IllegalArgumentException e) {
                throw new JsonParseException(e);
            }
        }
    }

    public static void setDateFormat(DateFormat dateFormat) {
        dateTypeAdapter.setFormat(dateFormat);
    }

    public static void setSqlDateFormat(DateFormat dateFormat) {
        sqlDateTypeAdapter.setFormat(dateFormat);
    }
}
